# Generated by Django 2.2.3 on 2019-07-18 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('dob', models.CharField(max_length=200, verbose_name='Date Of Birth')),
                ('email_id', models.EmailField(max_length=200, verbose_name='Email ID')),
                ('mobile_no', models.PositiveIntegerField(verbose_name='Mobile Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('objective', models.TextField(verbose_name='Objective')),
                ('brief_overview', models.TextField(verbose_name='Brief Overview')),
                ('tenth_marks', models.PositiveIntegerField(verbose_name='10 Marks')),
                ('twe_marks', models.PositiveIntegerField(verbose_name='12 Marks')),
                ('gradu_agg', models.PositiveIntegerField(verbose_name='Graduation Aggregate Marks')),
                ('tech_certi', models.TextField(verbose_name='Technical Certifications')),
                ('extra_curri', models.TextField(verbose_name='Extra Curricular Activities')),
                ('project', models.TextField(verbose_name='Projects Made')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
